/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestJNIConstructor */

#ifndef _Included_TestJNIConstructor
#define _Included_TestJNIConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIConstructor
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNIConstructor_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
