/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestJNINull */

#ifndef _Included_TestJNINull
#define _Included_TestJNINull
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNINull
 * Method:    gettingIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNINull_gettingIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
