/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestJNIField */

#ifndef _Included_TestJNIField
#define _Included_TestJNIField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIField
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNIField_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
