/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNI_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
